//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LottieViewConvert.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LottieViewConvert.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding To Path Allows Other Applications And Command Line Tools To Find Ffmpeg Automatically.
        /// </summary>
        public static string AddingToPathAllowsOtherApplicationsAndCommandLineToolsToFindFfmpegAutomatically {
            get {
                return ResourceManager.GetString("AddingToPathAllowsOtherApplicationsAndCommandLineToolsToFindFfmpegAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding to PATH allows other applications and command-line tools to find Gifski automatically.
        /// </summary>
        public static string AddingToPathAllowsOtherApplicationsAndCommandLineToolsToFindGifskiAutomatically {
            get {
                return ResourceManager.GetString("AddingToPathAllowsOtherApplicationsAndCommandLineToolsToFindGifskiAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Path.
        /// </summary>
        public static string AddToPath {
            get {
                return ResourceManager.GetString("AddToPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Loaded.
        /// </summary>
        public static string AllLoaded {
            get {
                return ResourceManager.GetString("AllLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A powerful cross-platform desktop application for converting TGS (Telegram Stickers) and Lottie animations to various formats including GIF, WebP, APNG, MP4, MKV, AVIF, and WebM. Support download sticker set from Telegram(name or link) directly. Built with modern technologies for optimal performance and user experience..
        /// </summary>
        public static string AppDesc {
            get {
                return ResourceManager.GetString("AppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottie View Convert.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottie &amp; TGS Animation Converter.
        /// </summary>
        public static string AppSubTitle {
            get {
                return ResourceManager.GetString("AppSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto detect.
        /// </summary>
        public static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Installation.
        /// </summary>
        public static string AutoInstallation {
            get {
                return ResourceManager.GetString("AutoInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Downloads And Installs Ffmpeg For Your Platform.
        /// </summary>
        public static string AutomaticallyDownloadsAndInstallsFfmpegForYourPlatform {
            get {
                return ResourceManager.GetString("AutomaticallyDownloadsAndInstallsFfmpegForYourPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically downloads and installs Gifski for your platform (x64 only).
        /// </summary>
        public static string AutomaticallyDownloadsAndInstallsGifskiForYourPlatformX64Only {
            get {
                return ResourceManager.GetString("AutomaticallyDownloadsAndInstallsGifskiForYourPlatformX64Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch convert done.
        /// </summary>
        public static string BatchConvertDone {
            get {
                return ResourceManager.GetString("BatchConvertDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch convert error.
        /// </summary>
        public static string BatchConvertError {
            get {
                return ResourceManager.GetString("BatchConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Config.
        /// </summary>
        public static string BotConfig {
            get {
                return ResourceManager.GetString("BotConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g: 123456789:ABCdefGHIjklMNOpqrsTUVwxyz.
        /// </summary>
        public static string BotTokenExample {
            get {
                return ResourceManager.GetString("BotTokenExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseDotDotDot {
            get {
                return ResourceManager.GetString("BrowseDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check failed.
        /// </summary>
        public static string CheckFailed {
            get {
                return ResourceManager.GetString("CheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose save location.
        /// </summary>
        public static string ChooseSaveLocation {
            get {
                return ResourceManager.GetString("ChooseSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme&apos;s color has been changed..
        /// </summary>
        public static string ColorChangedContent {
            get {
                return ResourceManager.GetString("ColorChangedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ColorChangedTitle {
            get {
                return ResourceManager.GetString("ColorChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent Tasks.
        /// </summary>
        public static string ConcurrentTasks {
            get {
                return ResourceManager.GetString("ConcurrentTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Discord API.
        /// </summary>
        public static string ConnectingToDiscordAPI {
            get {
                return ResourceManager.GetString("ConnectingToDiscordAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Complete.
        /// </summary>
        public static string ConversionComplete {
            get {
                return ResourceManager.GetString("ConversionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion stopped.
        /// </summary>
        public static string ConversionStopped {
            get {
                return ResourceManager.GetString("ConversionStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Failed.
        /// </summary>
        public static string ConvertFailed {
            get {
                return ResourceManager.GetString("ConvertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Succeeded.
        /// </summary>
        public static string ConvertSucceeded {
            get {
                return ResourceManager.GetString("ConvertSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwaggyMacro.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add to PATH.
        /// </summary>
        public static string CouldNotAddToPATH {
            get {
                return ResourceManager.GetString("CouldNotAddToPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a bot from @BotFather, and get the token..
        /// </summary>
        public static string CreateAndGetFromBotFather {
            get {
                return ResourceManager.GetString("CreateAndGetFromBotFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Custom.
        /// </summary>
        public static string CreateCustom {
            get {
                return ResourceManager.GetString("CreateCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current status: .
        /// </summary>
        public static string CurrentStatus {
            get {
                return ResourceManager.GetString("CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Dependencies {
            get {
                return ResourceManager.GetString("Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect.
        /// </summary>
        public static string Detect {
            get {
                return ResourceManager.GetString("Detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string Discord {
            get {
                return ResourceManager.GetString("Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Sticker Packs.
        /// </summary>
        public static string DiscordStickerPacks {
            get {
                return ResourceManager.GetString("DiscordStickerPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display language.
        /// </summary>
        public static string DisplayLanguage {
            get {
                return ResourceManager.GetString("DisplayLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cancelled.
        /// </summary>
        public static string DownloadCancelled {
            get {
                return ResourceManager.GetString("DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed.
        /// </summary>
        public static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Sticker/Emoji Set.
        /// </summary>
        public static string DownloadingStickerOrEmojiSet {
            get {
                return ResourceManager.GetString("DownloadingStickerOrEmojiSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Telegram Sticker/Emoji Set.
        /// </summary>
        public static string DownloadTgsStickerOrEmojiSetTitle {
            get {
                return ResourceManager.GetString("DownloadTgsStickerOrEmojiSetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you still want to install a local copy and add it to PATH?.
        /// </summary>
        public static string DoYouStillWantToInstallALocalCopyAndAddItToPATH {
            get {
                return ResourceManager.GetString("DoYouStillWantToInstallALocalCopyAndAddItToPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restart now?.
        /// </summary>
        public static string DoYouWantToRestartNow {
            get {
                return ResourceManager.GetString("DoYouWantToRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag folder here to convert!.
        /// </summary>
        public static string DragFolderHere {
            get {
                return ResourceManager.GetString("DragFolderHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag here to convert!.
        /// </summary>
        public static string DragHereToConvert {
            get {
                return ResourceManager.GetString("DragHereToConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag lottie file here.
        /// </summary>
        public static string DragLottieFileHere {
            get {
                return ResourceManager.GetString("DragLottieFileHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop to convet.
        /// </summary>
        public static string DropToConvert {
            get {
                return ResourceManager.GetString("DropToConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment PATH.
        /// </summary>
        public static string EnvironmentPATH {
            get {
                return ResourceManager.GetString("EnvironmentPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Files.
        /// </summary>
        public static string ExecutableFiles {
            get {
                return ResourceManager.GetString("ExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export current frame.
        /// </summary>
        public static string ExportCurrentFrame {
            get {
                return ResourceManager.GetString("ExportCurrentFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export succeeded.
        /// </summary>
        public static string ExportSucceeded {
            get {
                return ResourceManager.GetString("ExportSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add to PATH.
        /// </summary>
        public static string FailedToAddToPath {
            get {
                return ResourceManager.GetString("FailedToAddToPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Add To Path Via Registry.
        /// </summary>
        public static string FailedToAddToPathViaRegistry {
            get {
                return ResourceManager.GetString("FailedToAddToPathViaRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to browse.
        /// </summary>
        public static string FailedTobrowse {
            get {
                return ResourceManager.GetString("FailedTobrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load sticker packs.
        /// </summary>
        public static string FailedToLoadStickerPacks {
            get {
                return ResourceManager.GetString("FailedToLoadStickerPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove .
        /// </summary>
        public static string FailedToRemove {
            get {
                return ResourceManager.GetString("FailedToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Remove From Path.
        /// </summary>
        public static string FailedToRemoveFromPath {
            get {
                return ResourceManager.GetString("FailedToRemoveFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Update Any Shell Profile Files.
        /// </summary>
        public static string FailedToUpdateAnyShellProfileFiles {
            get {
                return ResourceManager.GetString("FailedToUpdateAnyShellProfileFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Multiple Format Support (GIF, WebP, APNG, MP4, MKV, AVIF, WebM).
        /// </summary>
        public static string FeatureLine1 {
            get {
                return ResourceManager.GetString("FeatureLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Concurrent tasks support for faster batch conversion.
        /// </summary>
        public static string FeatureLine10 {
            get {
                return ResourceManager.GetString("FeatureLine10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Parse &amp; Download Lottie Sticker set from Discord.
        /// </summary>
        public static string FeatureLine11 {
            get {
                return ResourceManager.GetString("FeatureLine11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Batch Processing for multiple files.
        /// </summary>
        public static string FeatureLine2 {
            get {
                return ResourceManager.GetString("FeatureLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • TGS &amp;amp; Lottie file support.
        /// </summary>
        public static string FeatureLine3 {
            get {
                return ResourceManager.GetString("FeatureLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Parse &amp; Download Sticker/Emoji set from Telegram (including .TGS, .JPG, .WebP, .PNG etc..).
        /// </summary>
        public static string FeatureLine4 {
            get {
                return ResourceManager.GetString("FeatureLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Customizable output settings.
        /// </summary>
        public static string FeatureLine5 {
            get {
                return ResourceManager.GetString("FeatureLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Cross-platform compatibility.
        /// </summary>
        public static string FeatureLine6 {
            get {
                return ResourceManager.GetString("FeatureLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Modern UI with SukiUI.
        /// </summary>
        public static string FeatureLine7 {
            get {
                return ResourceManager.GetString("FeatureLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • i18n Support, Only Chinese and English now..
        /// </summary>
        public static string FeatureLine8 {
            get {
                return ResourceManager.GetString("FeatureLine8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Automatic Installation of Dependencies: Simplify setup by automating gifski and FFmpeg installation.
        /// </summary>
        public static string FeatureLine9 {
            get {
                return ResourceManager.GetString("FeatureLine9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Discord sticker packs.
        /// </summary>
        public static string FetchingDiscordStickerPacks {
            get {
                return ResourceManager.GetString("FetchingDiscordStickerPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching metadata.
        /// </summary>
        public static string FetchingMetadata {
            get {
                return ResourceManager.GetString("FetchingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg Configuration.
        /// </summary>
        public static string FFmpegConfiguration {
            get {
                return ResourceManager.GetString("FFmpegConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ffmpeg Directory Added To Path Successfully. You May Need To Restart Applications To See The Change..
        /// </summary>
        public static string FfmpegDirectoryAddedToPathSuccessfullyYouMayNeedToRestartApplicationsToSeeTheChange {
            get {
                return ResourceManager.GetString("FfmpegDirectoryAddedToPathSuccessfullyYouMayNeedToRestartApplicationsToSeeTheChan" +
                        "ge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ffmpeg Directory Added To Shell Profiles.
        /// </summary>
        public static string FfmpegDirectoryAddedToShellProfiles {
            get {
                return ResourceManager.GetString("FfmpegDirectoryAddedToShellProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FfmpegDirectoryIsAlreadyConfiguredInShellProfiles.
        /// </summary>
        public static string FfmpegDirectoryIsAlreadyConfiguredInShellProfiles {
            get {
                return ResourceManager.GetString("FfmpegDirectoryIsAlreadyConfiguredInShellProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg directory is already in PATH.
        /// </summary>
        public static string FfmpegDirectoryIsAlreadyInPath {
            get {
                return ResourceManager.GetString("FfmpegDirectoryIsAlreadyInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg directory removed from shell profiles. Please restart your app to apply changes..
        /// </summary>
        public static string FFmpegDirectoryRemoved {
            get {
                return ResourceManager.GetString("FFmpegDirectoryRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ffmpeg Directory Removed From Path Successfully.
        /// </summary>
        public static string FfmpegDirectoryRemovedFromPathSuccessfully {
            get {
                return ResourceManager.GetString("FfmpegDirectoryRemovedFromPathSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ffmpeg Executable Not Found In Local Directory.
        /// </summary>
        public static string FfmpegExecutableNotFoundInLocalDirectory {
            get {
                return ResourceManager.GetString("FfmpegExecutableNotFoundInLocalDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg has been added to your PATH environment variable..
        /// </summary>
        public static string FFmpegHasBeenAddedToYourPathEnvironmentVariable {
            get {
                return ResourceManager.GetString("FFmpegHasBeenAddedToYourPathEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg installed successfully!.
        /// </summary>
        public static string FFmpegInstalledSuccessfully {
            get {
                return ResourceManager.GetString("FFmpegInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg is already available on your system at.
        /// </summary>
        public static string FFmpegIsAlreadyAvailableOnYourSystemAt {
            get {
                return ResourceManager.GetString("FFmpegIsAlreadyAvailableOnYourSystemAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg not found, please go to setting and install it by automatically or manually, without FFmpeg, converting to formats such as MKV, MP4, AVIF, APNG, and WebM is not supported..
        /// </summary>
        public static string FFmpegNotFoundContent {
            get {
                return ResourceManager.GetString("FFmpegNotFoundContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg not working.
        /// </summary>
        public static string FFmpegNotWorking {
            get {
                return ResourceManager.GetString("FFmpegNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg Path.
        /// </summary>
        public static string FFmpegPath {
            get {
                return ResourceManager.GetString("FFmpegPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-detect or browse to select FFmpeg executable.
        /// </summary>
        public static string FFmpegPathPlaceholder {
            get {
                return ResourceManager.GetString("FFmpegPathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loaded successfully.
        /// </summary>
        public static string FileLoadedSuccessfully {
            get {
                return ResourceManager.GetString("FileLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File load failed.
        /// </summary>
        public static string FileLoadFailed {
            get {
                return ResourceManager.GetString("FileLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS.
        /// </summary>
        public static string Fps {
            get {
                return ResourceManager.GetString("Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullScreen.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullScreen now.
        /// </summary>
        public static string FullScreenTip {
            get {
                return ResourceManager.GetString("FullScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM platform not supported for auto-installation, Please install manually.
        /// </summary>
        public static string GifskiAutoInstallOnlySupportsx64PlatformPleaseInstallManually {
            get {
                return ResourceManager.GetString("GifskiAutoInstallOnlySupportsx64PlatformPleaseInstallManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski Configuration.
        /// </summary>
        public static string GifskiConfiguration {
            get {
                return ResourceManager.GetString("GifskiConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski directory added to PATH successfully.
        /// </summary>
        public static string GifskiDirectoryAddedToPathSuccessfully {
            get {
                return ResourceManager.GetString("GifskiDirectoryAddedToPathSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski directory added to shell profiles..
        /// </summary>
        public static string GifskiDirectoryAddedToShellProfiles {
            get {
                return ResourceManager.GetString("GifskiDirectoryAddedToShellProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski directory is already configured in shell profiles.
        /// </summary>
        public static string GifskiDirectoryIsAlreadyConfiguredInShellProfiles {
            get {
                return ResourceManager.GetString("GifskiDirectoryIsAlreadyConfiguredInShellProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski directory is already in PATH.
        /// </summary>
        public static string GifskiDirectoryIsAlreadyInPath {
            get {
                return ResourceManager.GetString("GifskiDirectoryIsAlreadyInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski directory removed from PATH successfully..
        /// </summary>
        public static string GifskiDirectoryRemovedFromPathSuccessfully {
            get {
                return ResourceManager.GetString("GifskiDirectoryRemovedFromPathSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski executable not found in local directory.
        /// </summary>
        public static string GifskiExecutableNotFoundInLocalDirectory {
            get {
                return ResourceManager.GetString("GifskiExecutableNotFoundInLocalDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski has been added to your path environment variable.
        /// </summary>
        public static string GifskiHasBeenAddedToYourPathEnvironmentVariable {
            get {
                return ResourceManager.GetString("GifskiHasBeenAddedToYourPathEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski installed successfully.
        /// </summary>
        public static string GifskiInstalledSuccessfully {
            get {
                return ResourceManager.GetString("GifskiInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski Is Already Available On Your System At.
        /// </summary>
        public static string GifskiIsAlreadyAvailableOnYourSystemAt {
            get {
                return ResourceManager.GetString("GifskiIsAlreadyAvailableOnYourSystemAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski not found, please go to setting and install it by automatically or manually, without gifski, converting to formats such as gif is not supported..
        /// </summary>
        public static string GifskiNotFoundContent {
            get {
                return ResourceManager.GetString("GifskiNotFoundContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski not working.
        /// </summary>
        public static string GifskiNotWorking {
            get {
                return ResourceManager.GetString("GifskiNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gifski Path.
        /// </summary>
        public static string GifskiPath {
            get {
                return ResourceManager.GetString("GifskiPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it.
        /// </summary>
        public static string GotIt {
            get {
                return ResourceManager.GetString("GotIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use?.
        /// </summary>
        public static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just drag your lottie file(.tgs, .json) to the area..
        /// </summary>
        public static string HowToUseDescription {
            get {
                return ResourceManager.GetString("HowToUseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input sticker/emoji set name or link e.g (Godzi or https://t.me/addstickers/Godzi).
        /// </summary>
        public static string InputStickerOrEmojiSetNameOrLinkWatermark {
            get {
                return ResourceManager.GetString("InputStickerOrEmojiSetNameOrLinkWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input telegram bot token.
        /// </summary>
        public static string InputTelegramBotToken {
            get {
                return ResourceManager.GetString("InputTelegramBotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed.
        /// </summary>
        public static string InstallationFailed {
            get {
                return ResourceManager.GetString("InstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed successfully.
        /// </summary>
        public static string InstalledSuccessfully {
            get {
                return ResourceManager.GetString("InstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install FFmpeg Automatically.
        /// </summary>
        public static string InstallFFmpegAutomatically {
            get {
                return ResourceManager.GetString("InstallFFmpegAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Gifski Automatically.
        /// </summary>
        public static string InstallGifskiAutomatically {
            get {
                return ResourceManager.GetString("InstallGifskiAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid lottie file.
        /// </summary>
        public static string InvalidLottieFile {
            get {
                return ResourceManager.GetString("InvalidLottieFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or not working.
        /// </summary>
        public static string InvalidOrNotWorking {
            get {
                return ResourceManager.GetString("InvalidOrNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sticker/emoji set name or link.
        /// </summary>
        public static string InvalidStickerOrEmojiSetNameOrLink {
            get {
                return ResourceManager.GetString("InvalidStickerOrEmojiSetNameOrLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Key Features.
        /// </summary>
        public static string KeyFeatures {
            get {
                return ResourceManager.GetString("KeyFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed.
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed.
        /// </summary>
        public static string LanguageChangeDesc {
            get {
                return ResourceManager.GetString("LanguageChangeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart your app to switch language..
        /// </summary>
        public static string LanguageChangedMessage {
            get {
                return ResourceManager.GetString("LanguageChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed Restart.
        /// </summary>
        public static string LanguageChangedRestart {
            get {
                return ResourceManager.GetString("LanguageChangedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔗 Links &amp;amp; Resources.
        /// </summary>
        public static string LinkAndResx {
            get {
                return ResourceManager.GetString("LinkAndResx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load All.
        /// </summary>
        public static string LoadAll {
            get {
                return ResourceManager.GetString("LoadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed.
        /// </summary>
        public static string LoadFailed {
            get {
                return ResourceManager.GetString("LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingDotDotDot {
            get {
                return ResourceManager.GetString("LoadingDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading sticker packs....
        /// </summary>
        public static string LoadingStickerPacksDotDotDot {
            get {
                return ResourceManager.GetString("LoadingStickerPacksDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local FFmpeg directory does not exist.
        /// </summary>
        public static string LocalFfmpegDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("LocalFfmpegDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local gifski directory does not exist.
        /// </summary>
        public static string LocalGifskiDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("LocalGifskiDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottie JSON/TGS.
        /// </summary>
        public static string LottieJsonTgs {
            get {
                return ResourceManager.GetString("LottieJsonTgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Ffmpeg In System Path For Other Applications.
        /// </summary>
        public static string ManageFfmpegInSystemPathForOtherApplications {
            get {
                return ResourceManager.GetString("ManageFfmpegInSystemPathForOtherApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Gifski in system PATH for other applications.
        /// </summary>
        public static string ManageGifskiInSystemPathForOtherApplications {
            get {
                return ResourceManager.GetString("ManageGifskiInSystemPathForOtherApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoRestart failed, please restart manual..
        /// </summary>
        public static string ManualRestartMessage {
            get {
                return ResourceManager.GetString("ManualRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string NetworkSettings {
            get {
                return ResourceManager.GetString("NetworkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ffmpeg Entries Found In Shell Profiles To Remove.
        /// </summary>
        public static string NoFfmpegEntriesFoundInShellProfilesToRemove {
            get {
                return ResourceManager.GetString("NoFfmpegEntriesFoundInShellProfilesToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gifski entries found in shell profiles to remove.
        /// </summary>
        public static string NoGifskiEntriesFoundInShellProfilesToRemove {
            get {
                return ResourceManager.GetString("NoGifskiEntriesFoundInShellProfilesToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Later.
        /// </summary>
        public static string NoLater {
            get {
                return ResourceManager.GetString("NoLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string Notfound {
            get {
                return ResourceManager.GetString("Notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Use System FFmpeg.
        /// </summary>
        public static string NoUseSystemFFmpeg {
            get {
                return ResourceManager.GetString("NoUseSystemFFmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Use System gifski.
        /// </summary>
        public static string NoUseSystemGifski {
            get {
                return ResourceManager.GetString("NoUseSystemGifski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on Github.
        /// </summary>
        public static string OpenOnGithub {
            get {
                return ResourceManager.GetString("OpenOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenOutputFolder {
            get {
                return ResourceManager.GetString("OpenOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path.
        /// </summary>
        public static string OutputPath {
            get {
                return ResourceManager.GetString("OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to gifski executable (auto-detected if empty).
        /// </summary>
        public static string PathToGifskiExecutableAutoDetectedIfEmpty {
            get {
                return ResourceManager.GetString("PathToGifskiExecutableAutoDetectedIfEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Speed.
        /// </summary>
        public static string PlaySpeed {
            get {
                return ResourceManager.GetString("PlaySpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose output folder and files.
        /// </summary>
        public static string PleaseChooseOutputFolderAndFiles {
            get {
                return ResourceManager.GetString("PleaseChooseOutputFolderAndFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plase drag .tgs or .json file.
        /// </summary>
        public static string PleaseDragDotTgsOrDotJsonFile {
            get {
                return ResourceManager.GetString("PleaseDragDotTgsOrDotJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please setting telegram bot token.
        /// </summary>
        public static string PleaseSettingTelegramBotToken {
            get {
                return ResourceManager.GetString("PleaseSettingTelegramBotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing sticker packs.
        /// </summary>
        public static string ProcessingStickerPacks {
            get {
                return ResourceManager.GetString("ProcessingStickerPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Url.
        /// </summary>
        public static string ProxyUrl {
            get {
                return ResourceManager.GetString("ProxyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input proxy url, e.g: http://127.0.0.1:7890.
        /// </summary>
        public static string ProxyUrlSettingDesc {
            get {
                return ResourceManager.GetString("ProxyUrlSettingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readme.
        /// </summary>
        public static string Readme {
            get {
                return ResourceManager.GetString("Readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to download....
        /// </summary>
        public static string ReadyToDownloadDotDotDot {
            get {
                return ResourceManager.GetString("ReadyToDownloadDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from PATH.
        /// </summary>
        public static string RemoveFromPath {
            get {
                return ResourceManager.GetString("RemoveFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Dependencies:.
        /// </summary>
        public static string RequiredDependencies {
            get {
                return ResourceManager.GetString("RequiredDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Requirements.
        /// </summary>
        public static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetConfig {
            get {
                return ResourceManager.GetString("ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset failed.
        /// </summary>
        public static string ResetFailed {
            get {
                return ResourceManager.GetString("ResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save succeeded.
        /// </summary>
        public static string SaveSucceeded {
            get {
                return ResourceManager.GetString("SaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to.
        /// </summary>
        public static string SaveTo {
            get {
                return ResourceManager.GetString("SaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select FFmpeg Executable.
        /// </summary>
        public static string SelectFFmpegExecutable {
            get {
                return ResourceManager.GetString("SelectFFmpegExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Lottie JSON/TGS.
        /// </summary>
        public static string SelectLottieFile {
            get {
                return ResourceManager.GetString("SelectLottieFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Lottie folder.
        /// </summary>
        public static string SelectLottieFolder {
            get {
                return ResourceManager.GetString("SelectLottieFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Folder.
        /// </summary>
        public static string SelectOutputFolder {
            get {
                return ResourceManager.GetString("SelectOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sticker Pack.
        /// </summary>
        public static string SelectStickerPack {
            get {
                return ResourceManager.GetString("SelectStickerPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting reset.
        /// </summary>
        public static string SettingReset {
            get {
                return ResourceManager.GetString("SettingReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting saved.
        /// </summary>
        public static string SettingSaved {
            get {
                return ResourceManager.GetString("SettingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceFile {
            get {
                return ResourceManager.GetString("SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Folder.
        /// </summary>
        public static string SourceFolder {
            get {
                return ResourceManager.GetString("SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start batch convert.
        /// </summary>
        public static string StartBatchConvert {
            get {
                return ResourceManager.GetString("StartBatchConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting download.
        /// </summary>
        public static string StartingDownload {
            get {
                return ResourceManager.GetString("StartingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker.
        /// </summary>
        public static string Sticker {
            get {
                return ResourceManager.GetString("Sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker Download.
        /// </summary>
        public static string StickerDownload {
            get {
                return ResourceManager.GetString("StickerDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker/Emoji Set.
        /// </summary>
        public static string StickerOrEmojiSet {
            get {
                return ResourceManager.GetString("StickerOrEmojiSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sticker packs available.
        /// </summary>
        public static string StickerPacksAvailable {
            get {
                return ResourceManager.GetString("StickerPacksAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stickers.
        /// </summary>
        public static string Stickers {
            get {
                return ResourceManager.GetString("Stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping conversion....
        /// </summary>
        public static string StoppingConversion {
            get {
                return ResourceManager.GetString("StoppingConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tgs, .json.
        /// </summary>
        public static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support http and socks.
        /// </summary>
        public static string SupportHttpAndSocks {
            get {
                return ResourceManager.GetString("SupportHttpAndSocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to.
        /// </summary>
        public static string SwitchTo {
            get {
                return ResourceManager.GetString("SwitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛠️ Technology Stack.
        /// </summary>
        public static string TechStack {
            get {
                return ResourceManager.GetString("TechStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Framework: C# with Avalonia UI.
        /// </summary>
        public static string TechStackLine1 {
            get {
                return ResourceManager.GetString("TechStackLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Architecture: ReactiveUI (MVVM).
        /// </summary>
        public static string TechStackLine2 {
            get {
                return ResourceManager.GetString("TechStackLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • UI: SukiUI Components.
        /// </summary>
        public static string TechStackLine3 {
            get {
                return ResourceManager.GetString("TechStackLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Rendering: SkiaSharp Skottie.
        /// </summary>
        public static string TechStackLine4 {
            get {
                return ResourceManager.GetString("TechStackLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Processing: ImageMagick, gifski, FFmpeg.
        /// </summary>
        public static string TechStackLine5 {
            get {
                return ResourceManager.GetString("TechStackLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        public static string TelegramSettings {
            get {
                return ResourceManager.GetString("TelegramSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tgs Download.
        /// </summary>
        public static string TgsDownload {
            get {
                return ResourceManager.GetString("TgsDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme has been changed.
        /// </summary>
        public static string ThemeChangedContent {
            get {
                return ResourceManager.GetString("ThemeChangedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeChangedTitle {
            get {
                return ResourceManager.GetString("ThemeChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar.
        /// </summary>
        public static string TitleBar {
            get {
                return ResourceManager.GetString("TitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar tip.
        /// </summary>
        public static string TitleBarTip {
            get {
                return ResourceManager.GetString("TitleBarTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle menu.
        /// </summary>
        public static string ToggleMenuTip {
            get {
                return ResourceManager.GetString("ToggleMenuTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle mode.
        /// </summary>
        public static string ToggleMode {
            get {
                return ResourceManager.GetString("ToggleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Access User Environment Registry Key.
        /// </summary>
        public static string UnableToAccessUserEnvironmentRegistryKey {
            get {
                return ResourceManager.GetString("UnableToAccessUserEnvironmentRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unselected.
        /// </summary>
        public static string UnSelected {
            get {
                return ResourceManager.GetString("UnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported platform, try install it manually..
        /// </summary>
        public static string UnsupportedPlatform {
            get {
                return ResourceManager.GetString("UnsupportedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for browse or drop....
        /// </summary>
        public static string WaitingForBrowse {
            get {
                return ResourceManager.GetString("WaitingForBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for download sticker/emoji set....
        /// </summary>
        public static string WaitingForDownloadStickerOrEmojiSetDotDotDot {
            get {
                return ResourceManager.GetString("WaitingForDownloadStickerOrEmojiSetDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s this?.
        /// </summary>
        public static string WhatIsThis {
            get {
                return ResourceManager.GetString("WhatIsThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This&apos;s a simple application to convert Lottie animations to GIF, WEBP, APNG, PNG, MP4.This&apos;s a simple application to convert Lottie animations to GIF, WEBP, APNG, PNG, MP4..
        /// </summary>
        public static string WhatIsThisDescription {
            get {
                return ResourceManager.GetString("WhatIsThisDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Install &amp; Add to PATH.
        /// </summary>
        public static string YesInstallAndAddToPATH {
            get {
                return ResourceManager.GetString("YesInstallAndAddToPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Restart.
        /// </summary>
        public static string YesRestart {
            get {
                return ResourceManager.GetString("YesRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should restart the application to apply changes.
        /// </summary>
        public static string YouShouldRestartTheApplicationToApplyChanges {
            get {
                return ResourceManager.GetString("YouShouldRestartTheApplicationToApplyChanges", resourceCulture);
            }
        }
    }
}
